#!/bin/bash

/opt/conda/bin/python3

version=0.1

cd /tmp
mv ~/src/tdm_client.py .
python tdm_client.py install
mv ~/src/constellate-plugin .
pip install constellate-plugin/
rm -rf ~/src
cd -

# Book files not needed for notebooks.
rm -rf _toc.yml _config.yml .github/ book/ book-requirements.txt


python -m nltk.downloader stopwords wordnet

jupyter contrib nbextension install --user
jupyter nbextension install jupyter_contrib_nbextensions/nbextensions/toc2 --user
jupyter nbextension enable toc2/main
jupyter nbextension enable livemdpreview/livemdpreview
jupyter nbextension enable --py constellate_plugin

exec "$@"

