#!/bin/bash

/opt/conda/bin/python3

version=0.1

python -m nltk.downloader stopwords wordnet

jupyter contrib nbextension install --user
jupyter nbextension enable --py toc2/main
jupyter nbextension enable --py jupyter_notebookparams

exec "$@"